version: '3.8'

services:
  backend:
    image: ghcr.io/andrzejbab/klubster/backend:latest
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
      # Add other necessary backend env vars here

  frontend:
    image: ghcr.io/andrzejbab/klubster/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
    depends_on:
      - backend

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"